Lab 3
nextples/NSU-FIT-OS pull request #1
Opened 2024-04-08 12:20 UTC by nextples

2024-04-15 10:55 UTC, Silhouette22 requested changes

2024-04-15 10:55 UTC, Silhouette22 commented on lab-3/1/name-inverter.c
> +    char* inverted_path = calloc(sizeof(char), 1024);
У тебя здесь утечка памяти :)
Ты выделяешь память, а потом не освобождаешь.
Да и вообще, тут нет смысла задействовать кучу под временный буфер, лучше выделить эту память на стеке

2024-04-15 10:55 UTC, Silhouette22 commented on lab-3/1/name-inverter.c
> +    char* original_path = argv[1];
А что, если в твою прогу ничего не передать в качестве аргумента?

2024-04-15 10:55 UTC, Silhouette22 commented on lab-3/1/name-inverter.c
> +long get_last_slash_index(const char* string) {
Попробуй глянуть функцию `strrchr(3)`. Возможно, она поможет не писать свой велосипед :)

2024-04-15 10:55 UTC, Silhouette22 commented on lab-3/1/name-inverter.c
> +            char* new_file_name = calloc(sizeof(char), 100);
Вот ты активно используешь `calloc()`, но в коде я не увидел ни одного `free()`. Понимаешь, к чему я клоню? :)
У тебя в коде очень много утечек памяти. Если используешь для чего-то malloc/calloc, ты обязательно должен не забыть очистить выделенную память, когда закончил работу с ней.
А в рамках данной задачи тебе нигде и ни для чего не нужны ни malloc, ни calloc, так что давай от них избавимся и попробуем переписать код без них

2024-04-15 10:55 UTC, Silhouette22 commented on lab-3/1/name-inverter.c
> +        if (current_file->d_type == DT_REG) {
И давай еще добавим возможность рекурсивного обхода каталога. Т.е., чтобы можно было не только файлы в одной директории скопировать, но и все вложенные директории с их файлами и вложенными директориями тоже :)
Это несложно делается, ты справишься

2024-04-15 10:55 UTC, Silhouette22 commented on lab-3/1/name-inverter.c
> +            char* new_file_name = calloc(sizeof(char), 100);
И ты уверен, что 100 байт под имя файла хватит?

2024-04-22 13:44 UTC, nextples commented
Исправил все недочеты: 
1. В 3.1 добавил сохранение исходных прав для копий файлов 
2. В 3.2 добавил запуск необходимой программы через жесткие ссылки на исполняемый файл

2024-04-23 15:52 UTC, merged